version: 0.2
env:
  git-credential-helper: yes
phases:
  build:
    commands:
       - python --version
       - echo ${CODEBUILD_INITIATOR}
       - git clone https://github.com/jp30101995/gke-demo.git
       - git clone https://github.com/jp30101995/powershell.git
       - cd powershell
       - git checkout v1
       - ./demo.ps1
